import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/utils/AuthContext";
import { NotificationProvider } from "@/utils/NotificationContext";
import { BookingSocketProvider } from "@/utils/BookingSocketContext";
import { MessageSocketProvider } from "@/utils/MessageSocketContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700', '800'],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${poppins.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <AuthProvider>
          <NotificationProvider>
            <BookingSocketProvider>
              <MessageSocketProvider>
                {children}
              </MessageSocketProvider>
            </BookingSocketProvider>
          </NotificationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
