from app.routes.auth import router as auth_router
from app.routes.users import router as users_router
from app.routes.oauth import router as oauth_router
from app.routes.vacancies import router as vacancies_router
from app.routes.applications import router as applications_router
from app.routes.verifications import router as verifications_router
from app.routes.subscriptions import router as subscriptions_router
from app.routes.favorites import router as favorites_router
from app.routes.professionals import router as professionals_router
